name: Test application

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'

jobs:
  test:
    name: 'PHP ${{ matrix.php-version }}, ${{ matrix.dependencies}}'
    runs-on: ubuntu-20.04
    env:
      SYMFONY_DEPRECATIONS_HELPER: weak

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '7.1'
            dependencies: 'lowest'
          - php-version: '7.1'
          - php-version: '7.4'
          - php-version: '8.0'
          - php-version: '8.1'
            
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install and configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: 'pdo, pdo_sqlite'
          tools: 'composer:v2'

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist

      - name: Code Style
        run: composer cs:diff

      - name: phpstan
        run: composer phpstan
